### ISSUE TITLE
SAREF & SOSA hard to choose

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [oeg-upm/auroral-adapters-ontology#11]
The adapters ontology is using two ontologies for sensors. For instance, if I want to express that I have a temperature sensor that measures the property adpaters:ActsReasons I can only use SOSA, with saref as it is now the ontology it is not possible. 

Shall we keep only one of these two ontologies? or in other case, we should ensure that all the things can be expressed with both. But I think it would be better to use just one ontology.

**Comment by mariapoveda** [comment]
@AhlemRhayem analyze whether it is possible to cover the needs with SAREF ontology and if yes, go for SAREF modelling.
