### ISSUE TITLE
Is the error property needed?

### ISSUE THREAD

**Issue by mariapoveda** [oeg-upm/auroral-adapters-ontology#2]
Do we need to represent this property or is it internal use?

location-<location_id>/flood-<deviceid>/sensor/error: if different from 0, there is an error with the sensor

and

location-<location_id>/flood-<deviceid>/sensor/act_reasons: list of reasons which woke up the device: battery, button, periodic, poweron, sensor, alarm

 (from https://cloud.auroral.eu/index.php/f/98609)

Alentejo pilot.

**Comment by AhlemRhayem** [comment]
We define these properties as sub-classes of the Status concept.
