### ISSUE TITLE
"Status" field

### ISSUE THREAD

**Issue by queenpro** [oeg-upm/auroral-adapters-ontology#31]
Hi, I want suggest to include a tag "status" in the reading of energy production that can indicate if the data exposed was read with the right technical condition and can be considered validated from the source. This could help to distinguish for example a value of "0" read from non-correctly-working sensor from a really-read value of "0".
Thank you.

**Comment by AhlemRhayem** [comment]
We update the ontology by adding the DeviceStatus property.
