### ISSUE TITLE
Potential error in some URIs

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [oeg-upm/auroral-adapters-ontology#32]
Translating the owl file of the ontology into a different serialization is not possible because some terms have dots in their name which seems to be an error. For instance  adapters:PM.25Concentration produces an error, instead adapters:PM25Concentration does not

**Comment by AhlemRhayem** [comment]
I change the the dot by the ( _ ). the PM2.5Concentration becomes PM2_5Concentration
